### ISSUE TITLE
resource pack includes a cobblemon folder in assets

### ISSUE THREAD

**Issue by kcin2001** [Emery319/E19-CobblemonMinimapIcons#2]
for some reason you include a folder with all vanilla cobblemon textures and resolvers, the latter of which causes issues if the base mod ever updates its resolvers (which it has) and is seemingly not needed for the pack to function

**Comment by Emery319** [comment]
The cobblemon textures and resolvers are used to display unique Pokémon forms, such as Vivillon's different wing patterns. version 1.5.0 of cobblemon somehow removed Mimikyu's gender differences, which made the texture packs unloadable, and I've uploaded matches to 1.5.0 in modrinth! I've uploaded a new texture pack that matches 1.5.0 on modrinth, please try it out!

**Comment by Emery319** [comment]
The Cobblemon textures and resolvers are used to display unique Pokémon forms, such as Vivillon's different wing patterns. Version 1.5.0 of Cobblemon somehow removed Mimikyu's gender differences, which made the resource packs unloadable, and I've uploaded a new version that matches Cobblemon 1.5.0 on modrinth, please try it out!

https://modrinth.com/resourcepack/e19_cobblemon_minimap_icons/version/nHpLmt4T
