### ISSUE TITLE
pride pack vivillon shinies

### ISSUE THREAD

**Issue by Klefiki** [Emery319/E19-CobblemonMinimapIcons#4]
So I got a shiny scatterbug and finally decided to evolve it into the ace one with the new pride resource pack, but when evolved if the pack is active it removes the white body and does the default one on the actual pokemon. also just has them as a yellow dot on the mini map, is there a way to fix this?

**Comment by Klefiki** [comment]
this only happens if the mimap pack is active (sorry if i wasnt clear im bad at communicating)

**Comment by Emery319** [comment]
My email notifications had some issues, and I was busy editing new icons for Pride Month's Vivillon over the past few days. Sorry for the delayed response. Thank you for raising the issue. If you encounter any other problems with the resource pack, please feel free to let me know here.

**Comment by Klefiki** [comment]
For some reason I never got notified of this, but no worries and tysm for the hard work you do! I really like your pack :D
