### ISSUE TITLE
Shiny without indicator

### ISSUE THREAD

**Issue by Jszp03** [Emery319/E19-CobblemonMinimapIcons#7]
Suggestion, not issue. But can you please make a separate version (or include subfolder) that doesn't add sparkle to shiny icons?

A lot of people prefer to actually learn which pokemons are shiny, and look for them like in find wally

**Comment by Emery319** [comment]
Thank you for your suggestion. I can create unmarked Pokémon icons, but I didn’t keep the original files when I made them, so everything has to be done from scratch. This might take a lot of time, so please be patient.

**Comment by Emery319** [comment]
After the 1.2.4 update, the "regular_raw" and "shiny_raw" folders in the assets/xaerominimap/entity/icon/sprite directory contain unmarked icons.
