### ISSUE TITLE
Icons too small

### ISSUE THREAD

**Issue by Mortycio** [Emery319/E19-CobblemonMinimapIcons#9]
The Pokémon icons on the minimap are too small compared to Minecraft's vanilla mobs. To make them "acceptable," you need to increase the entity icon scale to 2.00, but that makes the other mob icons HUGE!

![2024-09-07_18 54 13](https://github.com/user-attachments/assets/48eacb9f-4318-409f-8baf-da8557a7870e)

**Comment by Emery319** [comment]
64x64 is the recommended icon resolution for Xaero’s Minimap. Enlarging the icons may result in some loss of clarity. This is a comparison between a 64-pixel icon using a 2.00 scale and a 128-pixel icon (Pokémon icon enlarged three times) using a 1.00 scale. 

![2024-09-08_13 16 37](https://github.com/user-attachments/assets/f7f2cb81-955c-4859-ab75-aa80c750c71e)![2024-09-08_13 17 03](https://github.com/user-attachments/assets/09566147-90b0-45ac-b925-022f10d3aa2d)

In this version, the size of the Pokémon icons is similar to that of the entity icons.

![2024-09-08_14 02 18](https://github.com/user-attachments/assets/b5176da7-1311-4755-95b9-d73e6863fbcf)

If this is acceptable to you, download this file -> [sprite.zip](https://github.com/Emery319/E19-CobblemonMinimapIcons/blob/main/sprite.zip), extract it, and paste the sprite folder into assets/xaerominimap/entity/icon, replacing the folder with the same name.

**Comment by Mortycio** [comment]
Thank you for clarifying and for the .zip!
